### ISSUE TITLE
Problem with My LP

### ISSUE THREAD

**Issue by aqeelabdulazeez** [LattePandaTeam/LattePanda-Win10-Software#12]
Dear guys, great works !
I  bought the LP board from DFROBOT before six month and everything seems to work properly at the first time and I turn off and left it but yesterday i try to turn on but i can't the following masseages appear as shown in the photo. kindly i need your help for fixed this problem or Do you have any suggestion or could you provide me anythings to fixe this problem  ?
Note: MY LP LattePanda - A Powerful Windows 10 Mini PC 4GB/64GB (Unactivated)
Thanks & regards

aqeel
![image1](https://user-images.githubusercontent.com/18182831/30145863-15b18c1a-939d-11e7-86ad-f7dd599640a2.JPG)
![image2](https://user-images.githubusercontent.com/18182831/30145862-15b000b6-939d-11e7-9752-1991a322228b.JPG)

**Comment by Lauren-ED209** [comment]
Dear friend, 
It looks like that your OS is broken. But seems that the bios still can run properly. So maybe it's caused by suddenly powering off when turning off the device or upgrading the Windows system. 

But the good news is the hardware should be ok according to your description. 
So I recommend that:
1. Refresh the BIOS based the tutorial on github first.
2. Reinstall the official OS from LattePanda.com/docs

Look forward to your update!
