### ISSUE TITLE
Bad instructions, access denied

### ISSUE THREAD

**Issue by JeffBship** [LattePandaTeam/LattePanda-Win10-Software#28]
Your instructions are incorrect.  Whenever you change your filenames or paths you need to update your readme.  There is no file "Install.bat"

When running the file "install_DF_S70CR100.bat" it results in 'access denied' for every driver.

I'm probably going to just send it back to Amazon for a refund.  Your product support is very sub-standard.

**Comment by Kondor2003** [comment]
Hello Jeff,
Just to be thorough, have you ran the CMD with Admin privileges? They do mention that in the instructions. Otherwise I cannot imagine how you can get an error message like "access denied". 
Second, I agree with you that they have not updated their install instructions based on the updated files and scrips that they have placed in that archive. You can take their instructions with a grain of salt, not literally by the word.
Let me know if running the CMD with Admin privileges has any effect.

Marius.
