### ISSUE TITLE
latte panda 4 / 64 , i want to use SD, BT and the others....

### ISSUE THREAD

**Issue by digerati73** [LattePandaTeam/LattePanda-Win10-Software#39]
i bought second-hand lattepanda 4/64, there is windows 10 pro at lattepanda.( DFR0419, Z8350)

i can't use micro SD card, and i can't use blue tooth, 

i found out that i need to install these accessory's driver to use them.

i found an article that explain how to install lattepanda drivers.

but there is a only link that is at google drive.

i downloaded that folder "4+64_drivers-20211114~~~~-001 "
but there is not a install program such as setup.exe.

how can i install all of these items at once ?

or 

which driver can i install to use MICRO SD CARD ?

THERE IS NOT AN SD CARD Folder,,,

i think , SD CARD driver folder is maybe SPI ? DPTF ? ISH ? PMIC ? PSS? TXEI ? BM?

I need a manual for installing drivers manually.

help me.... latte panda team

and congratulation for launching lattepanda 3 delta,

i think , lattepanda price is so high.

i think price is very important reference to buy something.

**Comment by alphaarea** [comment]
LattePanda uses some unconventional devices in order to get the x86 hardware on such a small PCB.

It is highly recommended to follow [the tutorial](https://docs.lattepanda.com/content/1st_edition/os/#re-install-windows-10-home) to install our system image, and then use the Windows system upgrade to upgrade to the new version

---------

If you must install the Windows image released by Microsoft and install the drivers manually.
1. Unzip all driver packages
2. Open Window Device Manager
3. Right-click the unknown device, click Upgrade Driver, manually locate the path where you extracted the driver and expect it to install successfully
