### ISSUE TITLE
Auto power on BIOS update Fail

### ISSUE THREAD

**Issue by zbc** [LattePandaTeam/LattePanda-Win10-Software#4]
I followed steps and it failed, is there anyway to recover lattepanda. Now it doesn't even turn on.

**Comment by Philanilenin** [comment]
i m having the exact same issue with two & them & i purchased 10 of them with licensing so i dnt know what to do now

**Comment by shimkh02** [comment]
How about Copy the default BIOS files to root of the USB flash disk?

And follow step again.

**Comment by Philanilenin** [comment]
It doesn’t work I still get a black screen



[image: signature-philani]



*From:* i.think [mailto:notifications@github.com]
*Sent:* Thursday, October 6, 2016 7:41 AM
*To:* LattePandaTeam/LattePanda-Win10-Software <
LattePanda-Win10-Software@noreply.github.com>
*Cc:* Philanilenin <philani@polycomp.co.za>; Comment <
comment@noreply.github.com>
*Subject:* Re: [LattePandaTeam/LattePanda-Win10-Software] Auto power on
BIOS update Fail (#4)



How about Copy the default BIOS files to root of the USB flash disk?

And follow step again.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LattePandaTeam/LattePanda-Win10-Software/issues/4#issuecomment-251871801>,
or mute the thread

**Comment by Philanilenin** [comment]
Hi

I recently purchased 10 latte panda but when I enter the bios I don’t see
where I can set it to auto start up after power failure can you help its
quite urgent.



[image: philani's-signature]

**Comment by Lauren-ED209** [comment]
Dear Philanilenin,

Check out this link please. They post a simple guide how to enable auto power on here!
http://www.lattepanda.com/forum/viewtopic.php?f=5&t=1187&p=5255&hilit=how+to+set+auto+power+on#p5255

Feel free to let me know if any other concern!

**Comment by Philanilenin** [comment]
Hi Lauren

Thanks for the response but the link you sent me does not really show me
how to do the actual update of the bios.



[image: philani's-signature]



*From:* Lauren [mailto:notifications@github.com]
*Sent:* Thursday, June 22, 2017 10:04 AM
*To:* LattePandaTeam/LattePanda-Win10-Software <
LattePanda-Win10-Software@noreply.github.com>
*Cc:* Philanilenin <philani@polycomp.co.za>; Comment <
comment@noreply.github.com>
*Subject:* Re: [LattePandaTeam/LattePanda-Win10-Software] Auto power on
BIOS update Fail (#4)



Dear Philanilenin,

Check out this link please. They post a simple guide how to enable auto
power on here!
http://www.lattepanda.com/forum/viewtopic.php?f=5&t=1187&p=5255&hilit=how+to+set+auto+power+on#p5255

Feel free to let me know if any other concern!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LattePandaTeam/LattePanda-Win10-Software/issues/4#issuecomment-310306891>,
or mute the thread

**Comment by Lauren-ED209** [comment]
Oh...What you need is a guide of how to update the bios? 
If so, please check the readme file here
https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Bios
We provided  a tutorial for re-flashing the bios. 

If not let me know what exactly you need. I just think you've updated the bios successfully. But don't know how to set it in the bios mode...

**Comment by shimkh02** [comment]
May be this could help with reprogramming bios chip.
http://www.lattepanda.com/forum/viewtopic.php?f=6&t=386

**Comment by Lauren-ED209** [comment]
Exactly yes. Lots of tinkers successfully reprogram the bios with this tutorial as I known.
