### ISSUE TITLE
WoL/WoWLan capability!

### ISSUE THREAD

**Issue by mappsys** [LattePandaTeam/LattePanda-Win10-Software#8]
Hi, is it possible to use Wake On Lan (wired) or WoWLAN (wireless) with LattePanda? How can i configure? i look in documentation in LattePanda site and i didn't find anything! Thanks

**Comment by popy911** [comment]
Why no any response answer?

**Comment by LattePanda** [comment]
Dear friends,

Sorry for the long term silence. After a meeting with our software and hardware team, we find that it's hard to support this feature in this version design because of the hardware issue. We will definitely combine this feature in next generation product. Please keep an eye on our updates...

Thanks for your great support. 
Feel free to let me know if you have any idea. 

Best
